### ISSUE TITLE
Update the high level diagram of Stonesoup

### ISSUE THREAD

**Issue by cmoulliard** [redhat-appstudio/architecture#48]
## Proposition

As it seems that the following diagram is not up to date, I propose that we review and update it:

![Screenshot 2023-02-07 at 12 27 32](https://user-images.githubusercontent.com/463790/217233199-df54d08b-79f6-4d74-9c67-15d231085957.png)

Part of the revision process, we should:

- Version the diagram like also include the github tag/release or commit sha link to be sure that it matches the last stuffs released
- Include a hyperlink top of each system component to point to the github repository hosting the code. If not possible, add text under the paragraph high level architecture
- Interaction between the system components should be represented to have a better idea about which component if the entry point (= aka master), which ones are the children
- Define where we will maintain the high level diagram

**Comment by ralphbean** [comment]
Back in 5ec5ef46b57fcacfe68f7db33826656c8d2add53 we just dropped the diagram rather than improve it.
