### ISSUE TITLE
Update the Application diagram and more

### ISSUE THREAD

**Issue by cmoulliard** [redhat-appstudio/architecture#49]
## Proposition

I propose to review/update the Application context diagram and that we rename the title of the paragraph. Why ? This is not clear for an external user to figure out what the Application context is ? Why do we use as word context, etc ?

![Screenshot 2023-02-07 at 12 28 09](https://user-images.githubusercontent.com/463790/217235437-dec42248-399d-4984-a6f5-68a68c14ef38.png)

Some of the points mentioned with the ticket #48 should also apply here

We should also:
- Add more text within the paragraph of the diagram to explain/detail what it covers
- Mention also that an Application will include many components where a component is a microservice, etc

**Comment by ralphbean** [comment]
https://github.com/redhat-appstudio/book/pull/127
