### ISSUE TITLE
Review the wording about Service(Context) component

### ISSUE THREAD

**Issue by cmoulliard** [redhat-appstudio/architecture#50]
## Proposition

I propose to review the wording of the title about the `Service(Context) component` as this is not clear for an external user to understand to what it refers

![Screenshot 2023-02-07 at 12 28 20](https://user-images.githubusercontent.com/463790/217237707-25a2ce74-c08a-4808-a108-1148b38c7591.png)

**Comment by ralphbean** [comment]
I think this got fixed up in 5ec5ef46b57fcacfe68f7db33826656c8d2add53

**Comment by cmoulliard** [comment]
This is not clear why you use the suffix `context`. A platform is composed of different systems which are able to execute a specific work and will propose different services. 
From this point of view, RHTAP or konflux represents a platform where we install different systems or services. Example: ocp cluster where argocd, tekton, etc have been installed
So, that would be better to name this section `Konflux platform` and to list the links about the different systems which compose it ;-)
